import { useEffect, useState } from "react";
import { Building2, ChevronLeft, ChevronRight, Eye, FileText, LoaderCircle, Mail, MapPin, Pencil, Phone, Plus, RefreshCw, Search, Trash2, X } from "lucide-react";
import { BUSINESS_PAGE_SIZE } from "../../utils/adminBusiness";
import { findBusinessTemplate } from "../../utils/businessTemplates";
import { businessRequest } from "../../lib/businesses/browser";
import BusinessDialog from "./BusinessDialog";

const toolClass = "flex h-11 w-11 shrink-0 items-center justify-center rounded-md text-zinc-500 hover:bg-zinc-100 hover:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary disabled:cursor-not-allowed disabled:opacity-40";

function BusinessTools({ record, onSelect }) {
  return <div className="flex shrink-0 items-center gap-1">{[{ mode: "view", label: "View", Icon: Eye }, { mode: "edit", label: "Edit", Icon: Pencil }, { mode: "delete", label: record.deletion_pending ? "Retry deletion of" : "Delete", Icon: Trash2 }].map(({ mode, label, Icon }) => <button key={mode} type="button" disabled={mode === "edit" && record.deletion_pending} onClick={() => onSelect({ id: record.id, mode })} className={toolClass + (mode === "delete" ? " text-primary" : "")} title={label + " business"} aria-label={label + " " + record.name}><Icon className="h-[18px] w-[18px]" aria-hidden="true" /></button>)}</div>;
}

function BusinessIdentity({ record }) {
  return <div className="flex min-w-0 items-center gap-3"><div className="flex h-12 w-16 shrink-0 items-center justify-center overflow-hidden rounded-md border border-zinc-100 bg-white-500 p-1.5">{record.logo?.url ? <img src={record.logo.url} alt={record.name + " logo"} width={64} height={48} className="h-full w-full object-contain" loading="lazy" /> : <Building2 className="h-5 w-5 text-zinc-400" aria-hidden="true" />}</div><div className="min-w-0"><span className="block break-words text-sm font-medium text-zinc-900">{record.name}</span><span className="mt-1 block text-xs text-zinc-500">{record.billing_mode === "custom" ? "Custom format" : (findBusinessTemplate(record.template_id, record.template_version)?.name || "Industrial") + " / v" + (record.template_version || 1)}</span>{record.deletion_pending && <span className="mt-1 block text-xs text-amber-700">Deletion pending</span>}</div></div>;
}

function BusinessNotes({ notes }) {
  const preview = notes?.length > 160 ? notes.slice(0, 160).trimEnd() + "..." : notes;
  return <p className="whitespace-pre-wrap break-words text-xs leading-5 text-zinc-500">{preview || "Not added"}</p>;
}

export default function Businesses() {
  const [search, setSearch] = useState("");
  const [page, setPage] = useState(1);
  const [result, setResult] = useState({ items: [], count: 0 });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [refresh, setRefresh] = useState(0);
  const [selection, setSelection] = useState(null);
  const [notice, setNotice] = useState("");
  useEffect(() => {
    const controller = new AbortController(); setLoading(true); setError("");
    const timer = setTimeout(() => {
      const params = new URLSearchParams({ search: search.trim().slice(0, 100), page: String(page) });
      businessRequest("/api/admin/businesses?" + params, { signal: controller.signal })
        .then((data) => { if (controller.signal.aborted) return; if (page > Math.max(1, Math.ceil(data.count / BUSINESS_PAGE_SIZE))) { setPage(1); return; } setResult(data); })
        .catch((cause) => { if (!controller.signal.aborted) setError(cause.message); })
        .finally(() => { if (!controller.signal.aborted) setLoading(false); });
    }, 250);
    return () => { clearTimeout(timer); controller.abort(); };
  }, [search, page, refresh]);
  useEffect(() => {
    const focus = () => { if (document.visibilityState === "visible" && !selection) setRefresh((value) => value + 1); };
    window.addEventListener("focus", focus); return () => window.removeEventListener("focus", focus);
  }, [selection]);
  const pages = Math.max(1, Math.ceil(result.count / BUSINESS_PAGE_SIZE));
  return <section aria-label="Business directory" className="min-w-0 space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="relative w-full min-w-0 sm:max-w-sm"><Search className="pointer-events-none absolute left-3 top-3.5 h-4 w-4 text-zinc-400" aria-hidden="true" /><input type="search" aria-label="Search businesses" placeholder="Search businesses..." maxLength={100} value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} className="h-11 w-full min-w-0 rounded-md border border-zinc-200 bg-white-500 pl-9 pr-11 text-base focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20 sm:text-sm" />{search && <button type="button" className={toolClass + " absolute right-0 top-0"} aria-label="Clear business search" title="Clear search" onClick={() => { setSearch(""); setPage(1); }}><X className="h-4 w-4" aria-hidden="true" /></button>}</div><div className="flex w-full items-center justify-between gap-3 sm:w-auto"><span className="text-xs tabular-nums text-zinc-500 sm:hidden">{loading ? "Loading..." : error ? "" : `${result.count} ${result.count === 1 ? "business" : "businesses"}`}</span><div className="flex items-center gap-2"><button type="button" disabled={loading} className={toolClass} onClick={() => setRefresh((value) => value + 1)} title="Refresh businesses" aria-label="Refresh businesses"><RefreshCw className="h-4 w-4" aria-hidden="true" /></button><button type="button" onClick={() => setSelection({ mode: "create" })} className="inline-flex min-h-[44px] items-center justify-center gap-2 rounded-md bg-primary px-4 py-2.5 text-sm font-medium text-primary-foreground hover:bg-primary-hover focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2"><Plus className="h-4 w-4" aria-hidden="true" />Create business</button></div></div></div>
    {notice && <div role="status" className="flex items-start justify-between gap-3 rounded-md border border-emerald-200 bg-emerald-50 px-4 py-2 text-sm leading-6 text-emerald-800"><span className="min-w-0 py-2">{notice}</span><button type="button" onClick={() => setNotice("")} aria-label="Dismiss business notification" title="Dismiss notification" className={toolClass}><X className="h-4 w-4" aria-hidden="true" /></button></div>}
    {loading ? <div role="status" className="flex min-h-[260px] items-center justify-center gap-2 text-sm text-zinc-500"><LoaderCircle className="h-5 w-5 animate-spin motion-reduce:animate-none" aria-hidden="true" />Loading businesses...</div> : error ? <div role="alert" className="border-y border-zinc-200 bg-white-500 px-4 py-6"><p className="text-sm leading-6 text-primary">{error}</p><button type="button" onClick={() => setRefresh((value) => value + 1)} className="mt-3 inline-flex min-h-[44px] items-center gap-2 rounded-md border border-zinc-200 px-4 text-sm text-zinc-700 focus-visible:ring-2 focus-visible:ring-primary"><RefreshCw className="h-4 w-4" aria-hidden="true" />Retry</button></div> : !result.items.length ? <div className="flex min-h-[280px] flex-col items-center justify-center border-y border-zinc-200 bg-white-500 px-4 py-8 text-center"><Building2 className="mb-3 h-8 w-8 text-zinc-300" aria-hidden="true" /><h2 className="text-base font-medium">{search ? "No matching businesses" : "No businesses yet"}</h2>{!search && <button type="button" onClick={() => setSelection({ mode: "create" })} className="mt-5 inline-flex min-h-[44px] items-center gap-2 rounded-md px-4 text-sm font-medium text-primary focus-visible:ring-2 focus-visible:ring-primary"><Plus className="h-4 w-4" aria-hidden="true" />Create business</button>}</div> : <>
      <ul className="grid gap-3 lg:hidden">{result.items.map((record) => <li key={record.id} className="min-w-0 rounded-lg border border-zinc-200 bg-white-500 p-4"><BusinessIdentity record={record} /><dl className="mt-4 space-y-3 text-sm"><div className="flex flex-wrap items-center gap-x-3 gap-y-1"><dt className="text-xs text-zinc-500">NTN</dt><dd className="break-all font-medium text-zinc-700">{record.ntn}</dd></div><div><dt className="sr-only">Email</dt><dd className="flex items-start gap-2 break-all text-zinc-600"><Mail className="mt-1 h-4 w-4 shrink-0 text-zinc-400" aria-hidden="true" />{record.email}</dd></div><div><dt className="sr-only">Phone</dt><dd className="flex items-start gap-2 break-all text-zinc-600"><Phone className="mt-1 h-4 w-4 shrink-0 text-zinc-400" aria-hidden="true" />{record.phone}</dd></div><div><dt className="sr-only">Address</dt><dd className="flex items-start gap-2 text-sm leading-6 text-zinc-500"><MapPin className="mt-1 h-4 w-4 shrink-0" aria-hidden="true" /><span className="min-w-0 break-words">{record.address}</span></dd></div>{record.special_notes && <div><dt className="mb-1 text-xs font-medium text-zinc-600">Special Notes and Instructions</dt><dd><BusinessNotes notes={record.special_notes} /></dd></div>}</dl><div className="mt-4 flex flex-wrap items-center justify-between gap-2 border-t border-zinc-100 pt-3"><span className="inline-flex items-center gap-1.5 text-xs text-zinc-400">{record.billing_format && <FileText className="h-4 w-4" aria-hidden="true" />}{record.billing_format ? "Billing format attached" : "Business details"}</span><BusinessTools record={record} onSelect={setSelection} /></div></li>)}</ul>
      <div className="hidden overflow-hidden rounded-lg border border-zinc-200 bg-white-500 lg:block"><div className="flex items-center justify-between border-b border-zinc-200 px-5 py-4"><h2 className="text-sm font-medium">Business directory</h2><span className="text-xs tabular-nums text-zinc-500">{result.count} {result.count === 1 ? "business" : "businesses"}</span></div><div className="overflow-x-auto"><table className="w-full min-w-[840px] table-fixed text-left text-sm"><caption className="sr-only">Businesses, contact details, special notes and instructions</caption><thead className="border-b border-zinc-100 bg-zinc-50 text-xs text-zinc-500"><tr><th scope="col" className="w-[27%] px-5 py-3 font-medium">Business</th><th scope="col" className="w-[12%] px-4 py-3 font-medium">NTN number</th><th scope="col" className="px-4 py-3 font-medium">Contact</th><th scope="col" className="w-[23%] px-4 py-3 font-medium">Special Notes and Instructions</th><th scope="col" className="w-[150px] px-4 py-3"><span className="sr-only">Actions</span></th></tr></thead><tbody className="divide-y divide-zinc-100">{result.items.map((record) => <tr key={record.id} className="hover:bg-zinc-50/60"><td className="px-5 py-5"><BusinessIdentity record={record} /></td><td className="break-all px-4 py-5 text-zinc-600">{record.ntn}</td><td className="px-4 py-5"><div className="break-all text-xs text-zinc-600">{record.email}</div><div className="mt-2 break-all text-xs text-zinc-500">{record.phone}</div></td><td className="px-4 py-5 align-top"><BusinessNotes notes={record.special_notes} /></td><td className="px-2 py-5"><BusinessTools record={record} onSelect={setSelection} /></td></tr>)}</tbody></table></div></div>
    </>}
    {!loading && !error && result.count > 0 && <div className="flex flex-wrap items-center justify-between gap-2 border-t border-zinc-200 pt-3 text-xs text-zinc-500"><span>{(page - 1) * BUSINESS_PAGE_SIZE + 1}-{Math.min(page * BUSINESS_PAGE_SIZE, result.count)} of {result.count}</span><div className="flex items-center gap-2"><button type="button" disabled={page <= 1} onClick={() => setPage((value) => value - 1)} className={toolClass} title="Previous businesses" aria-label="Previous businesses"><ChevronLeft className="h-4 w-4" aria-hidden="true" /></button><span className="tabular-nums">{page} / {pages}</span><button type="button" disabled={page >= pages} onClick={() => setPage((value) => value + 1)} className={toolClass} title="Next businesses" aria-label="Next businesses"><ChevronRight className="h-4 w-4" aria-hidden="true" /></button></div></div>}
    {selection && <BusinessDialog key={selection.id || "create"} selection={selection} onClose={() => setSelection(null)} onChanged={(message) => { setNotice(message); setRefresh((value) => value + 1); }} />}
  </section>;
}
