import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Link from "next/link";
import { Building2, ChevronDown, ChevronLeft, ChevronRight, Eye, FileText, LoaderCircle, Plus, Search, X } from "lucide-react";
import { formatQuotationAmount, formatQuotationDate, isQuotationId, QUOTATION_PAGE_SIZE } from "../../utils/adminQuotation";
import { quotationRequest } from "../../lib/quotations/browser";
import QuotationPicker from "./QuotationPicker";

const tools = "flex h-11 w-11 shrink-0 items-center justify-center rounded-md text-zinc-500 hover:bg-zinc-100 hover:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary disabled:opacity-40";
const createClass = "inline-flex min-h-[44px] items-center justify-center gap-2 rounded-md bg-primary px-4 py-3 text-sm font-medium text-primary-foreground hover:bg-primary-hover focus-visible:ring-2 focus-visible:ring-primary";

export default function Quotations() {
  const router = useRouter(); const filter = typeof router.query.business === "string" && isQuotationId(router.query.business) ? router.query.business : "";
  const [business, setBusiness] = useState(null); const [picker, setPicker] = useState(false);
  const [search, setSearch] = useState(""); const [page, setPage] = useState(1);
  const [result, setResult] = useState({ items: [], count: 0 }); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => {
    const controller = new AbortController(); setBusiness(null); setPage(1);
    if (filter) quotationRequest("/api/admin/quotations/options?" + new URLSearchParams({ kind: "business", id: filter }), { signal: controller.signal }).then((record) => { if (!controller.signal.aborted) setBusiness(record); }).catch(() => {});
    return () => controller.abort();
  }, [filter]);
  useEffect(() => {
    if (!router.isReady) return;
    const controller = new AbortController(); setLoading(true); setError("");
    const timer = setTimeout(() => {
      quotationRequest("/api/admin/quotations?" + new URLSearchParams({ business: filter, search, page: String(page) }), { signal: controller.signal })
        .then((data) => { if (!controller.signal.aborted) { const last = Math.max(1, Math.ceil(data.count / QUOTATION_PAGE_SIZE)); if (page > last) setPage(last); else setResult(data); } })
        .catch((cause) => { if (!controller.signal.aborted) setError(cause.message); })
        .finally(() => { if (!controller.signal.aborted) setLoading(false); });
    }, 200);
    return () => { clearTimeout(timer); controller.abort(); };
  }, [router.isReady, filter, search, page]);
  const choose = (record) => { setPage(1); setBusiness(record); router.push({ pathname: "/admin/quotations", query: { business: record.id } }, undefined, { shallow: true }); };
  const view = (record) => <Link href={"/admin/quotations/" + record.id}><a title="View quotation" aria-label={"View " + record.reference} className={tools}><Eye className="h-[18px] w-[18px]" aria-hidden="true" /></a></Link>;
  const newUrl = "/admin/quotations/new" + (filter ? "?business=" + filter : "");
  return <section className="min-w-0 space-y-4" aria-label="Quotation directory">
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="relative w-full sm:max-w-sm"><Search className="absolute left-3 top-3.5 h-4 w-4 text-zinc-400" aria-hidden="true" /><input type="search" value={search} maxLength={100} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Search quotations..." aria-label="Search quotations" className="h-11 w-full min-w-0 rounded-md border border-zinc-200 bg-white-500 pl-9 pr-3 text-base focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20 sm:text-sm" /></div><Link href={newUrl}><a className={createClass}><Plus className="h-4 w-4" aria-hidden="true" />Create quotation</a></Link></div>
    <div className="flex min-w-0 flex-wrap items-center justify-between gap-3 border-y border-zinc-200 py-3"><div className="flex min-w-0 max-w-full items-center gap-2"><button type="button" onClick={() => setPicker(true)} className="inline-flex min-h-[44px] min-w-0 items-center gap-2 rounded-md border border-zinc-200 bg-white-500 px-3 py-2 text-sm focus-visible:ring-2 focus-visible:ring-primary"><Building2 className="h-4 w-4 shrink-0 text-zinc-400" aria-hidden="true" /><span className="min-w-0 break-words text-left">{filter ? business?.name || "Selected business" : "All businesses"}</span><ChevronDown className="h-4 w-4 shrink-0 text-zinc-400" aria-hidden="true" /></button>{filter && <button type="button" onClick={() => { setPage(1); router.push("/admin/quotations", undefined, { shallow: true }); }} aria-label="Clear business filter" title="All businesses" className={tools}><X className="h-4 w-4" aria-hidden="true" /></button>}</div><span className="text-xs tabular-nums text-zinc-500">{loading ? "Loading..." : error ? "" : `${result.count} ${result.count === 1 ? "quotation" : "quotations"}`}</span></div>
    {loading ? <div role="status" className="flex min-h-[250px] items-center justify-center gap-2 text-sm text-zinc-500"><LoaderCircle className="h-5 w-5 animate-spin" aria-hidden="true" />Loading quotations...</div> : error ? <p role="alert" className="border-y border-zinc-200 bg-white-500 p-5 text-sm leading-6 text-primary">{error}</p> : !result.items.length ? <div className="flex min-h-[260px] flex-col items-center justify-center gap-3 border-y border-zinc-200 bg-white-500 px-4 text-center"><FileText className="h-8 w-8 text-zinc-300" aria-hidden="true" /><h2 className="text-base font-medium">{search ? "No matching quotations" : "No quotations yet"}</h2><Link href={newUrl}><a className="inline-flex min-h-[44px] items-center gap-2 rounded px-3 text-sm font-medium text-primary focus-visible:ring-2 focus-visible:ring-primary"><Plus className="h-4 w-4" aria-hidden="true" />Create quotation</a></Link></div> : <>
      <ul className="grid gap-3 lg:hidden">{result.items.map((record) => <li key={record.id} className="min-w-0 rounded-lg border border-zinc-200 bg-white-500 p-4"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><span className="block break-all text-sm font-medium text-zinc-900">{record.reference}</span><p className="mt-2 break-words text-sm text-zinc-700">{record.customer_company}</p><p className="mt-1 break-words text-xs text-zinc-500">{record.customer_name}</p></div>{view(record)}</div><p className="mt-4 flex items-start gap-2 break-words text-xs leading-5 text-zinc-500"><Building2 className="mt-0.5 h-4 w-4 shrink-0" aria-hidden="true" /><span className="min-w-0">{record.business_name}</span></p><div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-zinc-100 pt-3"><time dateTime={record.date} className="text-xs text-zinc-500">{formatQuotationDate(record.date)}</time><strong className="break-all text-sm font-medium tabular-nums">{formatQuotationAmount(record.total)}</strong></div></li>)}</ul>
      <div className="hidden overflow-x-auto rounded-lg border border-zinc-200 bg-white-500 lg:block"><table className="w-full min-w-[780px] table-fixed text-left text-sm"><caption className="sr-only">Saved quotations by business and customer</caption><thead className="border-b border-zinc-200 bg-zinc-50 text-xs text-zinc-500"><tr><th scope="col" className="w-[27%] px-5 py-3 font-medium">Quotation</th><th scope="col" className="px-4 py-3 font-medium">Customer</th><th scope="col" className="w-[110px] px-4 py-3 font-medium">Date</th><th scope="col" className="w-[170px] px-4 py-3 text-right font-medium">Total</th><th scope="col" className="w-[60px]"><span className="sr-only">View</span></th></tr></thead><tbody className="divide-y divide-zinc-100">{result.items.map((record) => <tr key={record.id} className="hover:bg-zinc-50"><th scope="row" className="break-all px-5 py-4 font-medium">{record.reference}<span className="mt-1 block break-words text-xs font-normal text-zinc-500">{record.business_name}</span></th><td className="break-words px-4 py-4">{record.customer_company}<span className="mt-1 block text-xs text-zinc-500">{record.customer_name}</span></td><td className="px-4 py-4 text-xs text-zinc-500">{formatQuotationDate(record.date)}</td><td className="break-all px-4 py-4 text-right font-medium tabular-nums">{formatQuotationAmount(record.total)}</td><td className="px-2 py-4">{view(record)}</td></tr>)}</tbody></table></div>
    </>}
    {!loading && !error && result.count > 0 && <div className="flex flex-wrap items-center justify-between gap-2 border-t border-zinc-200 pt-3 text-xs text-zinc-500"><span>{(page - 1) * QUOTATION_PAGE_SIZE + 1}-{Math.min(page * QUOTATION_PAGE_SIZE, result.count)} of {result.count}</span><div className="flex items-center gap-2"><button type="button" disabled={page <= 1} onClick={() => setPage((value) => value - 1)} className={tools} title="Previous quotations" aria-label="Previous quotations"><ChevronLeft className="h-4 w-4" aria-hidden="true" /></button><span>{page} / {Math.ceil(result.count / QUOTATION_PAGE_SIZE)}</span><button type="button" disabled={page * QUOTATION_PAGE_SIZE >= result.count} onClick={() => setPage((value) => value + 1)} className={tools} title="Next quotations" aria-label="Next quotations"><ChevronRight className="h-4 w-4" aria-hidden="true" /></button></div></div>}
    {picker && <QuotationPicker kind="business" onSelect={choose} onClose={() => setPicker(false)} />}
  </section>;
}
