import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/router";
import Link from "next/link";
import { ArrowLeft, Building2, ChevronDown, LoaderCircle, Plus, Save, Trash2, Users } from "lucide-react";
import { formatQuotationAmount, MAX_QUOTATION_ITEMS, normalizeQuotation, quotationExpiry, quotationSubtotal, quotationToday, validateQuotation } from "../../utils/adminQuotation";
import { quotationRequest } from "../../lib/quotations/browser";
import QuotationPicker from "./QuotationPicker";

const input = "min-h-[44px] w-full min-w-0 rounded-md border border-zinc-200 bg-white-500 px-3 py-2.5 text-base text-zinc-900 focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20 disabled:bg-zinc-50 sm:text-sm";
const tool = "flex h-11 w-11 shrink-0 items-center justify-center rounded-md text-zinc-500 hover:bg-zinc-100 hover:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary disabled:opacity-40";

export default function QuotationForm({ initialBusinessId = "" }) {
  const router = useRouter();
  const [business, setBusiness] = useState(null); const [customer, setCustomer] = useState(null);
  const [values, setValues] = useState(() => { const date = quotationToday(); return { date, valid_until: quotationExpiry(date), subject: "", notes: "", items: [] }; });
  const [picker, setPicker] = useState(null); const [businessLoading, setBusinessLoading] = useState(false);
  const [pending, setPending] = useState(false); const [error, setError] = useState(""); const [fields, setFields] = useState({});
  const busy = useRef(false); const request = useRef(null); const businessSelection = useRef(0); const mounted = useRef(true);
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; }; }, []);
  const chooseBusiness = async (record) => {
    const turn = ++businessSelection.current; setBusinessLoading(true); setBusiness(null); setError(""); setFields((current) => ({ ...current, business_id: "" }));
    try { const result = await quotationRequest("/api/admin/quotations/options?" + new URLSearchParams({ kind: "business", id: record.id })); if (mounted.current && turn === businessSelection.current) setBusiness(result); }
    catch (cause) { if (mounted.current && turn === businessSelection.current) setError(cause.message); }
    finally { if (mounted.current && turn === businessSelection.current) setBusinessLoading(false); }
  };
  useEffect(() => { if (initialBusinessId) chooseBusiness({ id: initialBusinessId }); }, [initialBusinessId]);
  useEffect(() => {
    const warn = (event) => { if (values.items.length && !busy.current) { event.preventDefault(); event.returnValue = ""; } };
    window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn);
  }, [values.items.length]);
  const change = (key, value) => { setValues((current) => ({ ...current, [key]: value })); setFields((current) => ({ ...current, [key]: "" })); };
  const itemChange = (index, key, value) => { setValues((current) => ({ ...current, items: current.items.map((item, position) => position === index ? { ...item, [key]: value } : item) })); setFields((current) => ({ ...current, [`items.${index}.${key}`]: "", items: "" })); };
  const payload = () => normalizeQuotation({ ...values, business_id: business?.id, business_revision: business?.revision, customer_id: customer?.id, customer_revision: customer?.revision });
  const addProducts = (records) => { setValues((current) => ({ ...current, items: [...current.items, ...records.filter((record) => !current.items.some((item) => item.product_id === record.id)).map((record) => ({ key: window.crypto.randomUUID(), product_id: record.id, revision: record.revision, name: record.name, description: record.name, quantity: "1", price: String(record.price) }))].slice(0, MAX_QUOTATION_ITEMS) })); setFields({}); };
  const submit = async (event) => {
    event.preventDefault(); if (busy.current || businessLoading) return;
    const body = payload(); const errors = validateQuotation(body); setFields(errors); setError("");
    if (!business?.quotation_layout && business) errors.business_id = "This custom format needs a layout mapping.";
    if (Object.keys(errors).length) { setFields({ ...errors }); document.getElementById("quote-" + Object.keys(errors)[0])?.focus(); return; }
    busy.current = true; setPending(true);
    const fingerprint = JSON.stringify(body);
    if (request.current?.fingerprint !== fingerprint) request.current = { fingerprint, id: window.crypto.randomUUID() };
    try { const saved = await quotationRequest("/api/admin/quotations", { method: "POST", body: { ...body, request_id: request.current.id } }); await router.push("/admin/quotations/" + saved.id); }
    catch (cause) { if (mounted.current) { setError(cause.message); setFields(cause.fields || {}); } }
    finally { busy.current = false; if (mounted.current) setPending(false); }
  };
  const total = quotationSubtotal(values.items);
  const canSave = Boolean(business?.quotation_layout && customer && values.items.length && !businessLoading);
  const errorText = (key) => fields[key] ? <p id={"quote-" + key + "-error"} className="mt-1.5 text-xs leading-5 text-primary">{fields[key]}</p> : null;
  const pickerButton = (kind, record, Icon) => <div className="min-w-0"><label className="mb-2 block text-sm font-medium text-zinc-700" htmlFor={"quote-" + kind + "_id"}>{kind === "business" ? "Business" : "Customer"} <span className="text-primary" aria-hidden="true">*</span></label><button id={"quote-" + kind + "_id"} type="button" disabled={pending || businessLoading && kind === "business"} aria-invalid={Boolean(fields[kind + "_id"])} aria-describedby={fields[kind + "_id"] ? "quote-" + kind + "_id-error" : undefined} onClick={() => setPicker(kind)} className={"flex min-h-[56px] w-full items-center gap-3 rounded-md border bg-white-500 px-3 py-3 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary disabled:opacity-50 " + (fields[kind + "_id"] ? "border-primary" : "border-zinc-200")}><Icon className="h-5 w-5 shrink-0 text-zinc-400" aria-hidden="true" /><span className="min-w-0 flex-1 break-words text-sm text-zinc-900">{businessLoading && kind === "business" ? "Loading business..." : record?.name || "Choose " + kind}{record && <span className="mt-1 block break-words text-xs leading-5 text-zinc-500">{kind === "business" ? record.quotation_layout?.name || "Format not configured" : record.company_name}</span>}</span><ChevronDown className="h-4 w-4 shrink-0 text-zinc-400" aria-hidden="true" /></button>{errorText(kind + "_id")}{kind === "business" && business && !business.quotation_layout && <p role="alert" className="mt-2 text-sm leading-6 text-primary">This uploaded format needs a layout mapping before a quotation can be saved.</p>}</div>;

  return <form onSubmit={submit} noValidate aria-busy={pending} className="min-w-0 space-y-6">
    <Link href="/admin/quotations"><a className="inline-flex min-h-[44px] items-center gap-2 rounded text-sm text-zinc-500 hover:text-primary focus-visible:ring-2 focus-visible:ring-primary"><ArrowLeft className="h-4 w-4" aria-hidden="true" />Quotations</a></Link>
    {error && <p role="alert" className="rounded-md border border-primary/20 bg-primary-light p-4 text-sm leading-6 text-primary">{error}</p>}
    <fieldset disabled={pending} className="min-w-0 space-y-5 border-y border-zinc-200 bg-white-500 px-4 py-5 sm:px-6">
      <legend className="sr-only">Quotation details</legend><h2 className="text-base font-medium">Quotation details</h2>
      <div className="grid min-w-0 gap-5 sm:grid-cols-2">{pickerButton("business", business, Building2)}{pickerButton("customer", customer, Users)}
        <div className="min-w-0"><label htmlFor="quote-date" className="mb-2 block text-sm font-medium text-zinc-700">Date <span className="text-primary" aria-hidden="true">*</span></label><input id="quote-date" type="date" min="2000-01-01" max="2099-12-31" required value={values.date} onChange={(event) => { const date = event.target.value; setValues((current) => ({ ...current, date, valid_until: current.valid_until === quotationExpiry(current.date) ? quotationExpiry(date) : current.valid_until })); }} aria-invalid={Boolean(fields.date)} aria-describedby={fields.date ? "quote-date-error" : undefined} className={input} />{errorText("date")}</div>
        <div className="min-w-0"><label htmlFor="quote-valid_until" className="mb-2 block text-sm font-medium text-zinc-700">Valid until <span className="text-primary" aria-hidden="true">*</span></label><input id="quote-valid_until" type="date" min={values.date || "2000-01-01"} max="2099-12-31" required value={values.valid_until} onChange={(event) => change("valid_until", event.target.value)} aria-invalid={Boolean(fields.valid_until)} aria-describedby={fields.valid_until ? "quote-valid_until-error" : undefined} className={input} />{errorText("valid_until")}</div>
      </div>
      {customer && <p className="break-words text-sm leading-6 text-zinc-500">{customer.address}<span className="mt-1 block break-all">{customer.phone} | {customer.email}</span></p>}
      <div><label htmlFor="quote-subject" className="mb-2 block text-sm font-medium text-zinc-700">Project / requirement (optional)</label><textarea id="quote-subject" rows={2} maxLength={500} value={values.subject} onChange={(event) => change("subject", event.target.value)} className={input + " resize-y"} aria-invalid={Boolean(fields.subject)} aria-describedby={fields.subject ? "quote-subject-error" : undefined} />{errorText("subject")}</div>
    </fieldset>
    <section aria-labelledby="quote-items-heading" className="min-w-0 space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3"><h2 id="quote-items-heading" className="text-base font-medium">Items <span className="ml-2 text-xs font-normal tabular-nums text-zinc-400">{values.items.length}</span></h2><button id="quote-items" type="button" disabled={pending || values.items.length >= MAX_QUOTATION_ITEMS} onClick={() => setPicker("product")} className="inline-flex min-h-[44px] items-center gap-2 rounded-md border border-zinc-200 bg-white-500 px-4 text-sm font-medium text-zinc-700 focus-visible:ring-2 focus-visible:ring-primary disabled:opacity-50"><Plus className="h-4 w-4" aria-hidden="true" />Add products</button></div>{errorText("items")}
      {!values.items.length ? <div className="flex min-h-[160px] items-center justify-center border-y border-dashed border-zinc-200 bg-white-500"><button type="button" disabled={pending} onClick={() => setPicker("product")} className="inline-flex min-h-[44px] items-center gap-2 rounded-md px-4 text-sm font-medium text-primary focus-visible:ring-2 focus-visible:ring-primary"><Plus className="h-4 w-4" aria-hidden="true" />Add products</button></div> : <ol className="space-y-3">{values.items.map((item, index) => <li key={item.key} className="min-w-0 rounded-lg border border-zinc-200 bg-white-500 p-4 sm:p-5"><div className="mb-3 flex min-w-0 items-start justify-between gap-3"><h3 className="min-w-0 break-words pt-2 text-sm font-medium"><span className="mr-2 text-zinc-400">{index + 1}.</span>{item.name}</h3><button type="button" disabled={pending} onClick={() => { setValues((current) => ({ ...current, items: current.items.filter((_, position) => position !== index) })); setFields({}); }} className={tool} title="Remove quotation item" aria-label={"Remove " + item.name}><Trash2 className="h-4 w-4" aria-hidden="true" /></button></div>
        <fieldset disabled={pending} className="grid min-w-0 gap-4 sm:grid-cols-[minmax(0,1fr)_100px_150px]"><legend className="sr-only">Item {index + 1}</legend><div className="min-w-0"><label htmlFor={`quote-items.${index}.description`} className="mb-2 block text-xs text-zinc-500">Description</label><textarea id={`quote-items.${index}.description`} rows={2} required maxLength={500} value={item.description} onChange={(event) => itemChange(index, "description", event.target.value)} className={input + " resize-y"} aria-invalid={Boolean(fields[`items.${index}.description`])} aria-describedby={fields[`items.${index}.description`] ? `quote-items.${index}.description-error` : undefined} />{errorText(`items.${index}.description`)}</div><div className="grid min-w-0 grid-cols-2 gap-3 sm:col-span-2 sm:grid-cols-[100px_minmax(0,1fr)]"><div className="min-w-0"><label htmlFor={`quote-items.${index}.quantity`} className="mb-2 block text-xs text-zinc-500">Quantity</label><input id={`quote-items.${index}.quantity`} type="text" inputMode="numeric" pattern="[0-9]*" maxLength={7} required value={item.quantity} onChange={(event) => itemChange(index, "quantity", event.target.value)} className={input + " tabular-nums"} aria-invalid={Boolean(fields[`items.${index}.quantity`])} aria-describedby={fields[`items.${index}.quantity`] ? `quote-items.${index}.quantity-error` : undefined} />{errorText(`items.${index}.quantity`)}</div><div className="min-w-0"><label htmlFor={`quote-items.${index}.price`} className="mb-2 block text-xs text-zinc-500">Unit price (PKR)</label><input id={`quote-items.${index}.price`} type="text" inputMode="numeric" pattern="[0-9]*" maxLength={10} required value={item.price} onChange={(event) => itemChange(index, "price", event.target.value)} className={input + " tabular-nums"} aria-invalid={Boolean(fields[`items.${index}.price`])} aria-describedby={fields[`items.${index}.price`] ? `quote-items.${index}.price-error` : undefined} />{errorText(`items.${index}.price`)}</div></div></fieldset><div className="mt-4 flex flex-wrap justify-between gap-2 border-t border-zinc-100 pt-3 text-sm"><span className="text-zinc-500">Amount</span><strong className="min-w-0 break-all font-medium tabular-nums text-zinc-900">{Number.isSafeInteger(Number(item.quantity) * Number(item.price)) && /^\d+$/.test(item.quantity) && /^\d+$/.test(item.price) ? formatQuotationAmount(Number(item.quantity) * Number(item.price)) : "-"}</strong></div>{errorText(`items.${index}.product_id`)}
      </li>)}</ol>}
    </section>
    <fieldset disabled={pending} className="min-w-0 space-y-4 border-y border-zinc-200 bg-white-500 px-4 py-5 sm:px-6"><legend className="sr-only">Notes and instructions</legend><h2 className="text-base font-medium">Notes and instructions</h2>{business?.special_notes && <details className="text-sm"><summary className="min-h-[44px] cursor-pointer rounded py-3 font-medium text-zinc-600 focus-visible:ring-2 focus-visible:ring-primary">Business notes</summary><p className="whitespace-pre-wrap break-words py-2 text-sm leading-6 text-zinc-500">{business.special_notes}</p></details>}<div><label htmlFor="quote-notes" className="mb-2 block text-sm text-zinc-700">Additional notes (optional)</label><textarea id="quote-notes" rows={4} maxLength={5000} value={values.notes} onChange={(event) => change("notes", event.target.value)} className={input + " resize-y"} aria-invalid={Boolean(fields.notes)} aria-describedby={fields.notes ? "quote-notes-error" : undefined} />{errorText("notes")}</div></fieldset>
    <footer className="sticky bottom-0 z-20 grid grid-cols-1 gap-3 border-t border-zinc-200 bg-white-500 px-4 py-4 shadow-t sm:flex sm:items-center sm:justify-between sm:px-6"><div className="flex flex-wrap items-center justify-between gap-2 sm:block"><span className="text-xs text-zinc-500">Total</span><strong className="min-w-0 break-all text-lg font-medium tabular-nums sm:ml-3">{Number.isSafeInteger(total) ? formatQuotationAmount(total) : "-"}</strong></div><button type="submit" disabled={pending || !canSave} className="inline-flex min-h-[44px] items-center justify-center gap-2 rounded-md bg-primary px-5 py-3 text-sm font-medium text-primary-foreground hover:bg-primary-hover focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 disabled:opacity-50">{pending ? <LoaderCircle className="h-4 w-4 animate-spin" aria-hidden="true" /> : <Save className="h-4 w-4" aria-hidden="true" />}{pending ? "Saving..." : "Save quotation"}</button></footer>
    {picker && <QuotationPicker key={picker} kind={picker} onClose={() => setPicker(null)} existingProducts={values.items.map((item) => item.product_id)} onSelect={picker === "business" ? chooseBusiness : picker === "customer" ? (record) => { setCustomer(record); setFields((current) => ({ ...current, customer_id: "" })); } : addProducts} />}
  </form>;
}
