import Image from "next/image";
import { ArrowUpRight, Building2, Mail, MapPin, Phone, SearchX } from "lucide-react";
import business from "../../data/business.json";
import { formatAmount, prototypeCustomers, prototypeDocuments, prototypeProducts } from "../../data/salesPrototype";

export default function SalesModulePreview({ module, query, onView }) {
  if (module === "business") {
    return <section aria-labelledby="business-heading" className="border-y border-zinc-200 bg-white-500 px-5 py-6 sm:px-7"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-md bg-primary-light text-primary"><Building2 className="h-5 w-5" aria-hidden="true" /></span><div><h2 id="business-heading" className="text-lg font-medium">{business.name}</h2><p className="mt-1 text-xs text-zinc-500">Industrial supply / Pakistan</p></div></div><dl className="mt-8 grid gap-7 sm:grid-cols-2"><div><dt className="text-xs text-zinc-500">Business name</dt><dd className="mt-2 text-sm">{business.name}</dd></div><div><dt className="text-xs text-zinc-500">Currency</dt><dd className="mt-2 text-sm">Pakistani rupee (PKR)</dd></div><div><dt className="text-xs text-zinc-500">Email</dt><dd className="mt-2 flex items-center gap-2 break-all text-sm"><Mail className="h-4 w-4 shrink-0 text-zinc-400" aria-hidden="true" />{business.email}</dd></div><div><dt className="text-xs text-zinc-500">Contact number</dt><dd className="mt-2 flex items-center gap-2 text-sm"><Phone className="h-4 w-4 text-zinc-400" aria-hidden="true" />{business.phoneDisplay}</dd></div><div className="sm:col-span-2"><dt className="text-xs text-zinc-500">Address</dt><dd className="mt-2 flex items-start gap-2 text-sm leading-6"><MapPin className="mt-1 h-4 w-4 shrink-0 text-zinc-400" aria-hidden="true" />{business.addressDisplay}</dd></div></dl></section>;
  }
  const search = query.trim().toLowerCase();
  const isProducts = module === "products";
  const records = (isProducts ? prototypeProducts : prototypeCustomers).filter((entry) => Object.values(entry).some((value) => typeof value === "string" && value.toLowerCase().includes(search)));
  const columns = isProducts ? ["Product", "Category", "Brand", "Sample price / PKR"] : ["Customer", "Industry", "City", "Contact", ""];
  return <section aria-label={isProducts ? "Sample products" : "Sample customers"} className="relative overflow-hidden rounded-lg border border-zinc-200 bg-white-500"><div className="flex items-center justify-between gap-4 px-5 py-5"><h2 className="text-sm font-medium">{isProducts ? "Product catalogue" : "Customer directory"}</h2><span className="text-xs text-zinc-500">{records.length} records</span></div><div className="relative overflow-x-auto"><table className="w-full min-w-[630px] text-left text-sm"><caption className="sr-only">{isProducts ? "Fictional product prices for design review" : "Fictional customers for design review"}</caption><thead className="border-y border-zinc-100 bg-zinc-50 text-xs text-zinc-500"><tr>{columns.map((column, index) => <th key={index} scope="col" className={"px-5 py-3 font-medium " + (isProducts && index === 3 ? "text-right" : "")}>{column || <span className="sr-only">Actions</span>}</th>)}</tr></thead><tbody className="divide-y divide-zinc-100">{records.map((entry) => <tr key={entry.id} className="hover:bg-zinc-50"><th scope="row" className="px-5 py-4 font-normal"><div className="flex items-center gap-3">{isProducts ? <span className="relative h-12 w-12 shrink-0 overflow-hidden rounded border border-zinc-100 bg-white-500"><Image src={entry.image} alt={entry.name + " product collection"} layout="fill" objectFit="contain" sizes="48px" /></span> : <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md bg-zinc-100 text-xs font-medium text-zinc-600">{entry.name.split(" ").slice(0, 2).map((word) => word[0]).join("")}</span>}<div><div className="font-medium text-zinc-800">{entry.name}</div><div className="mt-1 text-xs text-zinc-400">{entry.id}</div></div></div></th><td className="px-5 py-4 text-zinc-500">{isProducts ? entry.category : entry.industry}</td><td className="px-5 py-4 text-zinc-700">{isProducts ? entry.brand : entry.city}</td><td className={"px-5 py-4 " + (isProducts ? "text-right tabular-nums text-zinc-800" : "text-zinc-500")}>{isProducts ? formatAmount(entry.price) : entry.contact}</td>{!isProducts && <td className="px-3 py-4"><button type="button" title={"View a document for " + entry.name} aria-label={"View a document for " + entry.name} onClick={() => onView(prototypeDocuments.find((document) => document.customer === entry.name))} className="flex h-9 w-9 items-center justify-center rounded-md text-zinc-400 hover:bg-zinc-100 hover:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"><ArrowUpRight className="h-4 w-4" aria-hidden="true" /></button></td>}</tr>)}</tbody></table>{!records.length && <div className="flex min-h-[220px] flex-col items-center justify-center gap-3"><SearchX className="h-7 w-7 text-zinc-400" aria-hidden="true" /><p className="text-sm text-zinc-600">No matching records</p></div>}</div></section>;
}
